### ISSUE TITLE
No button in https://laces-lab.github.io/documentation to come back to LACES Home

### ISSUE THREAD

**Issue by Fuad-HH** [LACES-LAB/documentation#26]
Shouldn't there be a button on the top of the https://laces-lab.github.io/documentation page to return to LACES Home https://laces-lab.github.io? I mean if someone enters directly into the documentation and doesn't know or remember that the LACES Home directly, it's inconvenient to enter LACES Home

**Comment by jacobmerson** [comment]
That would be a good idea.
