### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Fuad-HH** [LACES-LAB/documentation#28]
Docsy now has the dark mode capability with a nice drop-down menu. 
https://www.docsy.dev/docs/adding-content/lookandfeel/#lightdark-mode-menu

If you allow, I can update docsy to 0.10 and the option will be available

**Comment by jacobmerson** [comment]
Sorry I missed this question. Feel free to update the version of docsy. Just make sure that the github action still works to deploy it.

**Comment by Fuad-HH** [comment]
Resolved in commit 96b9e63 .
