### ISSUE TITLE
Link to other websites

### ISSUE THREAD

**Issue by Fuad-HH** [LACES-LAB/documentation#6]
I wanted to put something on the FAQ but it is already on the scorec wiki. So I want to just add it to the main page of FAQs and link it to the SCOREC page. Is there any easy solution for this in Hugo? Or should I even do it or write it myself?

**Comment by jacobmerson** [comment]
You can use any markdown so a link can be added with `[link text](link url)`. See https://daringfireball.net/projects/markdown/syntax

Or am I misunderstanding what you are asking?

**Comment by Fuad-HH** [comment]
Yes, I meant a different thing. Actually, I wanted to add another FAQ but for that page, I don't want to write it, instead, I want the link to direct to another website. In other words, you see in this [FAQs Page](https://laces-lab.github.io/documentation/faqs/) some blue links. I want to create a blue link that will direct to a different website rather than going to our documentation website. These index links are automatically created when I create the corresponding file in the faq directory with the title.

**Comment by jacobmerson** [comment]
I would just create a new  page that has a link on it. That way it'll show up in the sidebar as well.
